### ISSUE TITLE
Testing This

### ISSUE THREAD

**Issue by NFLD99** [NFLD99/IssueTest#3]
this is some example code block test
```css
.messageCozy-2JPAPA .username-_4ZSMR::after {
  content: ;
  background: currentColor;
  top:0;
  left:0;
  right:0;
  bottom:0;
  position:absolute;
  opacity:0.3;
  border-radius:5px;
  z-index:-1;
  filter: invert(1);
}
```

---
Beep, boop, I'm [a bot](https://github.com/LeagueSandbox/IssueBot)! This issue was created by `@NFLD99[DEV]` in `#admin-commands`.
